SET foreign_key_checks = 0;
DELETE FROM region;
DELETE FROM chief;
DELETE FROM employee;
DELETE FROM category;
DELETE FROM sales;
SET foreign_key_checks = 1;

INSERT INTO region SET name='south';
INSERT INTO region SET name='north';
INSERT INTO region SET name='west';
INSERT INTO region SET name='east';
INSERT INTO category SET name='Sport';
INSERT INTO category SET name='Kitchen';
INSERT INTO category SET name='Phone';
SELECT id FROM region WHERE name='south' INTO @regionId;
INSERT INTO chief SET name='Denis', fk_region=@regionId;
SELECT id FROM chief WHERE name='Denis' INTO @chiefId;
INSERT INTO employee SET name='Adrian', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Denis' INTO @chiefId;
INSERT INTO employee SET name='Agnes', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Denis' INTO @chiefId;
INSERT INTO employee SET name='Nathan', fk_chief=@chiefId;
SELECT id FROM region WHERE name='north' INTO @regionId;
INSERT INTO chief SET name='Alice', fk_region=@regionId;
SELECT id FROM chief WHERE name='Alice' INTO @chiefId;
INSERT INTO employee SET name='Jean-Pierre', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Alice' INTO @chiefId;
INSERT INTO employee SET name='Fabrice', fk_chief=@chiefId;
INSERT INTO chief SET name='Arnaud', fk_region=@regionId;
SELECT id FROM chief WHERE name='Arnaud' INTO @chiefId;
INSERT INTO employee SET name='Sacha', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Arnaud' INTO @chiefId;
INSERT INTO employee SET name='Agathe', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Arnaud' INTO @chiefId;
INSERT INTO employee SET name='Adam', fk_chief=@chiefId;
SELECT id FROM region WHERE name='west' INTO @regionId;
INSERT INTO chief SET name='Hervé', fk_region=@regionId;
SELECT id FROM chief WHERE name='Hervé' INTO @chiefId;
INSERT INTO employee SET name='Xavier', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Hervé' INTO @chiefId;
INSERT INTO employee SET name='Christain', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Hervé' INTO @chiefId;
INSERT INTO employee SET name='Marie', fk_chief=@chiefId;
SELECT id FROM region WHERE name='east' INTO @regionId;
INSERT INTO chief SET name='Christophe', fk_region=@regionId;
SELECT id FROM chief WHERE name='Christophe' INTO @chiefId;
INSERT INTO employee SET name='Jules', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Christophe' INTO @chiefId;
INSERT INTO employee SET name='Pierre', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Christophe' INTO @chiefId;
INSERT INTO employee SET name='Jean', fk_chief=@chiefId;
INSERT INTO chief SET name='Mathieux', fk_region=@regionId;
SELECT id FROM chief WHERE name='Mathieux' INTO @chiefId;
INSERT INTO employee SET name='Quan', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Mathieux' INTO @chiefId;
INSERT INTO employee SET name='Anna', fk_chief=@chiefId;
SELECT id FROM chief WHERE name='Mathieux' INTO @chiefId;
INSERT INTO employee SET name='Elisabeth', fk_chief=@chiefId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=8, `dateSale`='2015-01-20', `totalSale`='6011', `cb`='99', `check`='1', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=33, `dateSale`='2015-01-20', `totalSale`='6127', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=4, `dateSale`='2015-01-20', `totalSale`='9983', `cb`='12', `check`='88', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-20', `totalSale`='3132', `cb`='79', `check`='21', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=28, `dateSale`='2015-01-20', `totalSale`='7800', `cb`='99', `check`='1', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=81, `dateSale`='2015-01-20', `totalSale`='9224', `cb`='24', `check`='76', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=56, `dateSale`='2015-01-20', `totalSale`='6481', `cb`='65', `check`='35', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=36, `dateSale`='2015-01-20', `totalSale`='2901', `cb`='66', `check`='34', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=82, `dateSale`='2015-01-20', `totalSale`='7289', `cb`='7', `check`='93', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=24, `dateSale`='2015-01-20', `totalSale`='8019', `cb`='81', `check`='19', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-20', `totalSale`='8938', `cb`='73', `check`='27', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-20', `totalSale`='9525', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=24, `dateSale`='2015-01-20', `totalSale`='5311', `cb`='56', `check`='44', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=45, `dateSale`='2015-01-20', `totalSale`='3472', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=84, `dateSale`='2015-01-20', `totalSale`='9616', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=95, `dateSale`='2015-01-20', `totalSale`='4247', `cb`='13', `check`='87', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=30, `dateSale`='2015-01-20', `totalSale`='1022', `cb`='12', `check`='88', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=33, `dateSale`='2015-01-20', `totalSale`='2216', `cb`='90', `check`='10', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=17, `dateSale`='2015-01-20', `totalSale`='2730', `cb`='25', `check`='75', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=48, `dateSale`='2015-01-20', `totalSale`='3463', `cb`='49', `check`='51', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-20', `totalSale`='1184', `cb`='31', `check`='69', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=6, `dateSale`='2015-01-20', `totalSale`='9431', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=35, `dateSale`='2015-01-20', `totalSale`='5807', `cb`='32', `check`='68', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=7, `dateSale`='2015-01-20', `totalSale`='7093', `cb`='23', `check`='77', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-20', `totalSale`='479', `cb`='84', `check`='16', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-20', `totalSale`='6934', `cb`='10', `check`='90', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=83, `dateSale`='2015-01-20', `totalSale`='9320', `cb`='15', `check`='85', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=53, `dateSale`='2015-01-20', `totalSale`='9611', `cb`='28', `check`='72', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=85, `dateSale`='2015-01-20', `totalSale`='6070', `cb`='57', `check`='43', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=54, `dateSale`='2015-01-20', `totalSale`='2456', `cb`='96', `check`='4', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=46, `dateSale`='2015-01-20', `totalSale`='7189', `cb`='31', `check`='69', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=81, `dateSale`='2015-01-20', `totalSale`='2011', `cb`='6', `check`='94', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=34, `dateSale`='2015-01-20', `totalSale`='2442', `cb`='87', `check`='13', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=16, `dateSale`='2015-01-20', `totalSale`='9921', `cb`='91', `check`='9', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=4, `dateSale`='2015-01-20', `totalSale`='6468', `cb`='30', `check`='70', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=69, `dateSale`='2015-01-20', `totalSale`='2244', `cb`='76', `check`='24', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=83, `dateSale`='2015-01-20', `totalSale`='4797', `cb`='69', `check`='31', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=89, `dateSale`='2015-01-20', `totalSale`='5727', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-20', `totalSale`='2868', `cb`='71', `check`='29', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=7, `dateSale`='2015-01-20', `totalSale`='4502', `cb`='72', `check`='28', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=64, `dateSale`='2015-01-20', `totalSale`='1861', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=67, `dateSale`='2015-01-20', `totalSale`='47', `cb`='75', `check`='25', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=81, `dateSale`='2015-01-20', `totalSale`='3705', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=57, `dateSale`='2015-01-20', `totalSale`='2921', `cb`='79', `check`='21', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=58, `dateSale`='2015-01-20', `totalSale`='4436', `cb`='67', `check`='33', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=49, `dateSale`='2015-01-20', `totalSale`='3347', `cb`='94', `check`='6', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=53, `dateSale`='2015-01-20', `totalSale`='3134', `cb`='27', `check`='73', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=71, `dateSale`='2015-01-20', `totalSale`='3975', `cb`='31', `check`='69', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=98, `dateSale`='2015-01-20', `totalSale`='1181', `cb`='61', `check`='39', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-20', `totalSale`='8676', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=13, `dateSale`='2015-01-20', `totalSale`='8719', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-21', `totalSale`='63', `cb`='45', `check`='55', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=94, `dateSale`='2015-01-21', `totalSale`='1577', `cb`='58', `check`='42', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=94, `dateSale`='2015-01-21', `totalSale`='7893', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=13, `dateSale`='2015-01-21', `totalSale`='8558', `cb`='74', `check`='26', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=50, `dateSale`='2015-01-21', `totalSale`='7802', `cb`='88', `check`='12', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=70, `dateSale`='2015-01-21', `totalSale`='364', `cb`='26', `check`='74', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-21', `totalSale`='1634', `cb`='75', `check`='25', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=79, `dateSale`='2015-01-21', `totalSale`='5374', `cb`='66', `check`='34', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=30, `dateSale`='2015-01-21', `totalSale`='1579', `cb`='67', `check`='33', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-21', `totalSale`='2613', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-21', `totalSale`='6114', `cb`='13', `check`='87', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=63, `dateSale`='2015-01-21', `totalSale`='6722', `cb`='56', `check`='44', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=96, `dateSale`='2015-01-21', `totalSale`='1481', `cb`='11', `check`='89', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=15, `dateSale`='2015-01-21', `totalSale`='2550', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=67, `dateSale`='2015-01-21', `totalSale`='6374', `cb`='67', `check`='33', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=75, `dateSale`='2015-01-21', `totalSale`='8186', `cb`='88', `check`='12', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=11, `dateSale`='2015-01-21', `totalSale`='5126', `cb`='40', `check`='60', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-21', `totalSale`='7708', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=39, `dateSale`='2015-01-21', `totalSale`='2611', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=79, `dateSale`='2015-01-21', `totalSale`='1190', `cb`='17', `check`='83', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-21', `totalSale`='2956', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-21', `totalSale`='7634', `cb`='61', `check`='39', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=30, `dateSale`='2015-01-21', `totalSale`='9961', `cb`='53', `check`='47', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-21', `totalSale`='6581', `cb`='5', `check`='95', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=62, `dateSale`='2015-01-21', `totalSale`='3688', `cb`='62', `check`='38', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=67, `dateSale`='2015-01-21', `totalSale`='9469', `cb`='48', `check`='52', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=16, `dateSale`='2015-01-21', `totalSale`='9667', `cb`='93', `check`='7', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=69, `dateSale`='2015-01-21', `totalSale`='5031', `cb`='24', `check`='76', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=71, `dateSale`='2015-01-21', `totalSale`='808', `cb`='6', `check`='94', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=82, `dateSale`='2015-01-21', `totalSale`='1852', `cb`='72', `check`='28', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=0, `dateSale`='2015-01-21', `totalSale`='1626', `cb`='49', `check`='51', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=98, `dateSale`='2015-01-21', `totalSale`='1751', `cb`='63', `check`='37', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=45, `dateSale`='2015-01-21', `totalSale`='6903', `cb`='67', `check`='33', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=31, `dateSale`='2015-01-21', `totalSale`='1080', `cb`='79', `check`='21', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-21', `totalSale`='1893', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=81, `dateSale`='2015-01-21', `totalSale`='4912', `cb`='41', `check`='59', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-21', `totalSale`='2438', `cb`='48', `check`='52', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=78, `dateSale`='2015-01-21', `totalSale`='5680', `cb`='58', `check`='42', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=4, `dateSale`='2015-01-21', `totalSale`='9042', `cb`='88', `check`='12', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=23, `dateSale`='2015-01-21', `totalSale`='9301', `cb`='86', `check`='14', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=29, `dateSale`='2015-01-21', `totalSale`='1096', `cb`='50', `check`='50', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=46, `dateSale`='2015-01-21', `totalSale`='5862', `cb`='29', `check`='71', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-21', `totalSale`='7097', `cb`='69', `check`='31', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-21', `totalSale`='1382', `cb`='70', `check`='30', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=63, `dateSale`='2015-01-21', `totalSale`='9405', `cb`='30', `check`='70', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=94, `dateSale`='2015-01-21', `totalSale`='5030', `cb`='7', `check`='93', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=64, `dateSale`='2015-01-21', `totalSale`='4', `cb`='31', `check`='69', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=66, `dateSale`='2015-01-21', `totalSale`='2218', `cb`='8', `check`='92', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-21', `totalSale`='3079', `cb`='68', `check`='32', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-21', `totalSale`='866', `cb`='71', `check`='29', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=93, `dateSale`='2015-01-21', `totalSale`='9639', `cb`='65', `check`='35', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=92, `dateSale`='2015-01-22', `totalSale`='6541', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=4, `dateSale`='2015-01-22', `totalSale`='2836', `cb`='32', `check`='68', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=4, `dateSale`='2015-01-22', `totalSale`='1818', `cb`='7', `check`='93', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-22', `totalSale`='924', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=47, `dateSale`='2015-01-22', `totalSale`='1001', `cb`='12', `check`='88', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=95, `dateSale`='2015-01-22', `totalSale`='4663', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=63, `dateSale`='2015-01-22', `totalSale`='1155', `cb`='36', `check`='64', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=66, `dateSale`='2015-01-22', `totalSale`='9637', `cb`='39', `check`='61', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=77, `dateSale`='2015-01-22', `totalSale`='1769', `cb`='52', `check`='48', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=85, `dateSale`='2015-01-22', `totalSale`='2281', `cb`='84', `check`='16', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=34, `dateSale`='2015-01-22', `totalSale`='9518', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-22', `totalSale`='496', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=52, `dateSale`='2015-01-22', `totalSale`='953', `cb`='49', `check`='51', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=25, `dateSale`='2015-01-22', `totalSale`='6336', `cb`='53', `check`='47', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=76, `dateSale`='2015-01-22', `totalSale`='8967', `cb`='19', `check`='81', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-22', `totalSale`='652', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=83, `dateSale`='2015-01-22', `totalSale`='5619', `cb`='73', `check`='27', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=93, `dateSale`='2015-01-22', `totalSale`='6492', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=25, `dateSale`='2015-01-22', `totalSale`='7320', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=87, `dateSale`='2015-01-22', `totalSale`='982', `cb`='24', `check`='76', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=15, `dateSale`='2015-01-22', `totalSale`='836', `cb`='1', `check`='99', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=36, `dateSale`='2015-01-22', `totalSale`='9804', `cb`='92', `check`='8', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=47, `dateSale`='2015-01-22', `totalSale`='2891', `cb`='34', `check`='66', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-22', `totalSale`='9934', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=10, `dateSale`='2015-01-22', `totalSale`='5369', `cb`='40', `check`='60', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=75, `dateSale`='2015-01-22', `totalSale`='4435', `cb`='23', `check`='77', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-22', `totalSale`='2891', `cb`='19', `check`='81', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=32, `dateSale`='2015-01-22', `totalSale`='870', `cb`='97', `check`='3', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=86, `dateSale`='2015-01-22', `totalSale`='2132', `cb`='34', `check`='66', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-22', `totalSale`='9976', `cb`='66', `check`='34', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=19, `dateSale`='2015-01-22', `totalSale`='6549', `cb`='20', `check`='80', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-22', `totalSale`='8947', `cb`='49', `check`='51', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=85, `dateSale`='2015-01-22', `totalSale`='5001', `cb`='48', `check`='52', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=76, `dateSale`='2015-01-22', `totalSale`='9332', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-22', `totalSale`='8611', `cb`='93', `check`='7', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=71, `dateSale`='2015-01-22', `totalSale`='1158', `cb`='61', `check`='39', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=84, `dateSale`='2015-01-22', `totalSale`='4228', `cb`='8', `check`='92', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=20, `dateSale`='2015-01-22', `totalSale`='7588', `cb`='17', `check`='83', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-22', `totalSale`='4140', `cb`='84', `check`='16', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=26, `dateSale`='2015-01-22', `totalSale`='7734', `cb`='42', `check`='58', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=25, `dateSale`='2015-01-22', `totalSale`='7657', `cb`='9', `check`='91', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=29, `dateSale`='2015-01-22', `totalSale`='7739', `cb`='20', `check`='80', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=46, `dateSale`='2015-01-22', `totalSale`='9451', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=32, `dateSale`='2015-01-22', `totalSale`='3160', `cb`='84', `check`='16', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-22', `totalSale`='7751', `cb`='65', `check`='35', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=44, `dateSale`='2015-01-22', `totalSale`='3933', `cb`='63', `check`='37', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=88, `dateSale`='2015-01-22', `totalSale`='1433', `cb`='92', `check`='8', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-22', `totalSale`='4693', `cb`='22', `check`='78', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=68, `dateSale`='2015-01-22', `totalSale`='1768', `cb`='24', `check`='76', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=13, `dateSale`='2015-01-22', `totalSale`='9521', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-22', `totalSale`='2381', `cb`='7', `check`='93', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=96, `dateSale`='2015-01-23', `totalSale`='8628', `cb`='63', `check`='37', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=54, `dateSale`='2015-01-23', `totalSale`='6235', `cb`='48', `check`='52', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=96, `dateSale`='2015-01-23', `totalSale`='9152', `cb`='98', `check`='2', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=44, `dateSale`='2015-01-23', `totalSale`='5493', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=78, `dateSale`='2015-01-23', `totalSale`='3538', `cb`='28', `check`='72', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-23', `totalSale`='7200', `cb`='1', `check`='99', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-23', `totalSale`='3162', `cb`='8', `check`='92', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=20, `dateSale`='2015-01-23', `totalSale`='7347', `cb`='17', `check`='83', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=40, `dateSale`='2015-01-23', `totalSale`='2998', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=27, `dateSale`='2015-01-23', `totalSale`='5091', `cb`='19', `check`='81', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=46, `dateSale`='2015-01-23', `totalSale`='5167', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=76, `dateSale`='2015-01-23', `totalSale`='4577', `cb`='83', `check`='17', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=26, `dateSale`='2015-01-23', `totalSale`='1619', `cb`='81', `check`='19', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=57, `dateSale`='2015-01-23', `totalSale`='789', `cb`='73', `check`='27', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=95, `dateSale`='2015-01-23', `totalSale`='4106', `cb`='90', `check`='10', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=69, `dateSale`='2015-01-23', `totalSale`='8499', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=56, `dateSale`='2015-01-23', `totalSale`='9842', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=88, `dateSale`='2015-01-23', `totalSale`='6657', `cb`='22', `check`='78', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=62, `dateSale`='2015-01-23', `totalSale`='3718', `cb`='59', `check`='41', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=6, `dateSale`='2015-01-23', `totalSale`='1200', `cb`='40', `check`='60', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=49, `dateSale`='2015-01-23', `totalSale`='8344', `cb`='65', `check`='35', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-23', `totalSale`='9675', `cb`='24', `check`='76', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=0, `dateSale`='2015-01-23', `totalSale`='1739', `cb`='83', `check`='17', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=36, `dateSale`='2015-01-23', `totalSale`='1354', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-23', `totalSale`='8985', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=64, `dateSale`='2015-01-23', `totalSale`='816', `cb`='93', `check`='7', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=0, `dateSale`='2015-01-23', `totalSale`='8986', `cb`='86', `check`='14', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=30, `dateSale`='2015-01-23', `totalSale`='6371', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=22, `dateSale`='2015-01-23', `totalSale`='9228', `cb`='3', `check`='97', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=54, `dateSale`='2015-01-23', `totalSale`='5712', `cb`='82', `check`='18', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=23, `dateSale`='2015-01-23', `totalSale`='3286', `cb`='78', `check`='22', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-23', `totalSale`='7071', `cb`='25', `check`='75', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=5, `dateSale`='2015-01-23', `totalSale`='2408', `cb`='64', `check`='36', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=63, `dateSale`='2015-01-23', `totalSale`='2293', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=10, `dateSale`='2015-01-23', `totalSale`='2978', `cb`='92', `check`='8', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=87, `dateSale`='2015-01-23', `totalSale`='1456', `cb`='25', `check`='75', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=49, `dateSale`='2015-01-23', `totalSale`='38', `cb`='18', `check`='82', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=71, `dateSale`='2015-01-23', `totalSale`='5173', `cb`='83', `check`='17', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-23', `totalSale`='178', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=7, `dateSale`='2015-01-23', `totalSale`='8939', `cb`='6', `check`='94', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-23', `totalSale`='818', `cb`='53', `check`='47', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-23', `totalSale`='8379', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=14, `dateSale`='2015-01-23', `totalSale`='318', `cb`='14', `check`='86', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=9, `dateSale`='2015-01-23', `totalSale`='6023', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=65, `dateSale`='2015-01-23', `totalSale`='6644', `cb`='58', `check`='42', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=27, `dateSale`='2015-01-23', `totalSale`='4711', `cb`='45', `check`='55', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=80, `dateSale`='2015-01-23', `totalSale`='4463', `cb`='93', `check`='7', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=80, `dateSale`='2015-01-23', `totalSale`='8526', `cb`='88', `check`='12', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=41, `dateSale`='2015-01-23', `totalSale`='9770', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=69, `dateSale`='2015-01-23', `totalSale`='4292', `cb`='4', `check`='96', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=87, `dateSale`='2015-01-23', `totalSale`='7120', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=29, `dateSale`='2015-01-24', `totalSale`='5309', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=75, `dateSale`='2015-01-24', `totalSale`='9533', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=96, `dateSale`='2015-01-24', `totalSale`='7332', `cb`='74', `check`='26', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=31, `dateSale`='2015-01-24', `totalSale`='9519', `cb`='13', `check`='87', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=12, `dateSale`='2015-01-24', `totalSale`='9712', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=15, `dateSale`='2015-01-24', `totalSale`='7396', `cb`='5', `check`='95', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=96, `dateSale`='2015-01-24', `totalSale`='7920', `cb`='62', `check`='38', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=67, `dateSale`='2015-01-24', `totalSale`='6442', `cb`='32', `check`='68', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=45, `dateSale`='2015-01-24', `totalSale`='9749', `cb`='97', `check`='3', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=28, `dateSale`='2015-01-24', `totalSale`='7436', `cb`='25', `check`='75', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-24', `totalSale`='780', `cb`='72', `check`='28', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=2, `dateSale`='2015-01-24', `totalSale`='715', `cb`='25', `check`='75', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-24', `totalSale`='8095', `cb`='23', `check`='77', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-24', `totalSale`='6159', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=83, `dateSale`='2015-01-24', `totalSale`='1019', `cb`='41', `check`='59', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=13, `dateSale`='2015-01-24', `totalSale`='279', `cb`='61', `check`='39', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-24', `totalSale`='1190', `cb`='11', `check`='89', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=18, `dateSale`='2015-01-24', `totalSale`='2241', `cb`='95', `check`='5', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=70, `dateSale`='2015-01-24', `totalSale`='5372', `cb`='93', `check`='7', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=62, `dateSale`='2015-01-24', `totalSale`='7711', `cb`='69', `check`='31', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-24', `totalSale`='887', `cb`='28', `check`='72', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=68, `dateSale`='2015-01-24', `totalSale`='8596', `cb`='50', `check`='50', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=16, `dateSale`='2015-01-24', `totalSale`='338', `cb`='59', `check`='41', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-24', `totalSale`='5211', `cb`='42', `check`='58', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=68, `dateSale`='2015-01-24', `totalSale`='6018', `cb`='71', `check`='29', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=33, `dateSale`='2015-01-24', `totalSale`='7256', `cb`='2', `check`='98', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-24', `totalSale`='8885', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=63, `dateSale`='2015-01-24', `totalSale`='851', `cb`='66', `check`='34', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=1, `dateSale`='2015-01-24', `totalSale`='8541', `cb`='72', `check`='28', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=54, `dateSale`='2015-01-24', `totalSale`='1755', `cb`='98', `check`='2', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=86, `dateSale`='2015-01-24', `totalSale`='9374', `cb`='5', `check`='95', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=33, `dateSale`='2015-01-24', `totalSale`='5668', `cb`='95', `check`='5', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-24', `totalSale`='4566', `cb`='60', `check`='40', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-24', `totalSale`='2954', `cb`='56', `check`='44', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=60, `dateSale`='2015-01-24', `totalSale`='2563', `cb`='27', `check`='73', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=80, `dateSale`='2015-01-24', `totalSale`='9548', `cb`='98', `check`='2', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=66, `dateSale`='2015-01-24', `totalSale`='3883', `cb`='31', `check`='69', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=19, `dateSale`='2015-01-24', `totalSale`='6945', `cb`='18', `check`='82', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=17, `dateSale`='2015-01-24', `totalSale`='9706', `cb`='94', `check`='6', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=83, `dateSale`='2015-01-24', `totalSale`='5299', `cb`='48', `check`='52', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=8, `dateSale`='2015-01-24', `totalSale`='8600', `cb`='1', `check`='99', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=38, `dateSale`='2015-01-24', `totalSale`='8616', `cb`='29', `check`='71', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=36, `dateSale`='2015-01-24', `totalSale`='4777', `cb`='87', `check`='13', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=15, `dateSale`='2015-01-24', `totalSale`='682', `cb`='39', `check`='61', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=80, `dateSale`='2015-01-24', `totalSale`='7518', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-24', `totalSale`='543', `cb`='62', `check`='38', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-24', `totalSale`='9980', `cb`='58', `check`='42', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=10, `dateSale`='2015-01-24', `totalSale`='3181', `cb`='59', `check`='41', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=45, `dateSale`='2015-01-24', `totalSale`='4695', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=46, `dateSale`='2015-01-24', `totalSale`='4732', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=44, `dateSale`='2015-01-24', `totalSale`='7208', `cb`='28', `check`='72', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adrian' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=85, `dateSale`='2015-01-25', `totalSale`='9826', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=11, `dateSale`='2015-01-25', `totalSale`='9658', `cb`='30', `check`='70', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=98, `dateSale`='2015-01-25', `totalSale`='7891', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agnes' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=14, `dateSale`='2015-01-25', `totalSale`='723', `cb`='42', `check`='58', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=52, `dateSale`='2015-01-25', `totalSale`='7472', `cb`='63', `check`='37', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=73, `dateSale`='2015-01-25', `totalSale`='655', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Nathan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=54, `dateSale`='2015-01-25', `totalSale`='9657', `cb`='67', `check`='33', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=20, `dateSale`='2015-01-25', `totalSale`='2768', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=65, `dateSale`='2015-01-25', `totalSale`='7672', `cb`='60', `check`='40', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean-Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=25, `dateSale`='2015-01-25', `totalSale`='8423', `cb`='34', `check`='66', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=2, `dateSale`='2015-01-25', `totalSale`='5805', `cb`='21', `check`='79', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=10, `dateSale`='2015-01-25', `totalSale`='4187', `cb`='8', `check`='92', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Fabrice' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=79, `dateSale`='2015-01-25', `totalSale`='4733', `cb`='7', `check`='93', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=38, `dateSale`='2015-01-25', `totalSale`='4976', `cb`='11', `check`='89', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=29, `dateSale`='2015-01-25', `totalSale`='4880', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Sacha' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=43, `dateSale`='2015-01-25', `totalSale`='4668', `cb`='98', `check`='2', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=12, `dateSale`='2015-01-25', `totalSale`='8138', `cb`='89', `check`='11', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=29, `dateSale`='2015-01-25', `totalSale`='2913', `cb`='85', `check`='15', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Agathe' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=87, `dateSale`='2015-01-25', `totalSale`='9889', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=37, `dateSale`='2015-01-25', `totalSale`='373', `cb`='88', `check`='12', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-25', `totalSale`='8435', `cb`='1', `check`='99', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Adam' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=94, `dateSale`='2015-01-25', `totalSale`='5598', `cb`='80', `check`='20', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=28, `dateSale`='2015-01-25', `totalSale`='6228', `cb`='23', `check`='77', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=80, `dateSale`='2015-01-25', `totalSale`='2279', `cb`='95', `check`='5', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Xavier' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=67, `dateSale`='2015-01-25', `totalSale`='3604', `cb`='77', `check`='23', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=12, `dateSale`='2015-01-25', `totalSale`='6102', `cb`='22', `check`='78', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=6, `dateSale`='2015-01-25', `totalSale`='721', `cb`='6', `check`='94', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Christain' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=82, `dateSale`='2015-01-25', `totalSale`='3307', `cb`='1', `check`='99', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=11, `dateSale`='2015-01-25', `totalSale`='5104', `cb`='29', `check`='71', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=74, `dateSale`='2015-01-25', `totalSale`='3898', `cb`='79', `check`='21', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Marie' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=78, `dateSale`='2015-01-25', `totalSale`='3595', `cb`='79', `check`='21', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=21, `dateSale`='2015-01-25', `totalSale`='1504', `cb`='40', `check`='60', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=84, `dateSale`='2015-01-25', `totalSale`='6203', `cb`='75', `check`='25', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jules' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=50, `dateSale`='2015-01-25', `totalSale`='7773', `cb`='76', `check`='24', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=58, `dateSale`='2015-01-25', `totalSale`='8006', `cb`='32', `check`='68', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=90, `dateSale`='2015-01-25', `totalSale`='5468', `cb`='99', `check`='1', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Pierre' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=91, `dateSale`='2015-01-25', `totalSale`='1254', `cb`='45', `check`='55', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=64, `dateSale`='2015-01-25', `totalSale`='3000', `cb`='34', `check`='66', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=42, `dateSale`='2015-01-25', `totalSale`='9124', `cb`='9', `check`='91', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Jean' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=7, `dateSale`='2015-01-25', `totalSale`='5464', `cb`='37', `check`='63', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=68, `dateSale`='2015-01-25', `totalSale`='2418', `cb`='4', `check`='96', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=65, `dateSale`='2015-01-25', `totalSale`='1287', `cb`='43', `check`='57', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Quan' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=97, `dateSale`='2015-01-25', `totalSale`='4043', `cb`='18', `check`='82', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=22, `dateSale`='2015-01-25', `totalSale`='3020', `cb`='55', `check`='45', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=78, `dateSale`='2015-01-25', `totalSale`='8575', `cb`='4', `check`='96', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Anna' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=66, `dateSale`='2015-01-25', `totalSale`='6070', `cb`='59', `check`='41', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=66, `dateSale`='2015-01-25', `totalSale`='3378', `cb`='33', `check`='67', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=32, `dateSale`='2015-01-25', `totalSale`='5285', `cb`='30', `check`='70', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM employee WHERE name='Elisabeth' INTO @employeeId;
SELECT id FROM category WHERE name='Sport' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=26, `dateSale`='2015-01-25', `totalSale`='1124', `cb`='38', `check`='62', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Kitchen' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=61, `dateSale`='2015-01-25', `totalSale`='69', `cb`='45', `check`='55', `fk_employee`=@employeeId, `fk_category`=@categoryId;
SELECT id FROM category WHERE name='Phone' INTO @categoryId;
INSERT INTO sales SET `salesNumber`=20, `dateSale`='2015-01-25', `totalSale`='7271', `cb`='46', `check`='54', `fk_employee`=@employeeId, `fk_category`=@categoryId;